language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-frontend ./udagram-frontend

# Tagging
  - docker tag udagram-api-feed  bolobala/udagram-api-feed:v9
  - docker tag udagram-api-user  bolobala/udagram-api-user:v9
  - docker tag udagram-reverseproxy  bolobala/udagram-reverseproxy:v9
  - docker tag udagram-frontend  bolobala/udagram-frontend:local

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push bolobala/udagram-api-feed:v9
  - docker push bolobala/udagram-api-user:v9
  - docker push bolobala/udagram-reverseproxy:v9
  - docker push bolobala/udagram-frontend:local
  